name: Bizz CI/CD

on:
  push:
    branches: [main]
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: web4application/bizz

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ---------- Python ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run PyTests
        run: |
          if [ -d tests ]; then pytest -q; else echo "No Python tests"; fi

      # ---------- Node / TypeScript ----------
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node deps
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Run JS/TS tests
        run: |
          if [ -f package.json ]; then npm test --if-present; fi

      # ---------- Docker build & push ----------
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # ---------- Optional Vercel deploy ----------
      - name: Deploy Front-End to Vercel (main only)
        if: github.ref == 'refs/heads/main' && secrets.VERCEL_TOKEN != ''
        run: |
          npm i -g vercel@latest
          vercel --confirm --token ${{ secrets.VERCEL_TOKEN }} --prod --yes
